### ISSUE TITLE
models requirements with basic napkin installation

### ISSUE THREAD

**Issue by C00kie-** [adulau/napkin-text-analysis#1]
It looks like we need to download additional models :

OSError: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by adulau** [comment]
We have two options:

- Adding in the documentation the two lines to add the models
- or the hardcore version, forcing the download/install of the models missing

**Comment by C00kie-** [comment]
Force install is a good option :+1: at least the English one for the example

**Comment by adulau** [comment]
Great, I'll add it. if you find something else, let me know.

**Comment by adulau** [comment]
It's fixed in https://github.com/adulau/napkin-text-analysis/commit/1192d17e86adcdf282d9c18c9a5f0e52eeca47f1#diff-57e240106308df1e9f39bfd9b5f3bd1bdf784e0d007e268956ccfcefcbec689eL55
